os: osx
osx_image: xcode9
language: objective-c
xcode_project: ios-travis-sample.xcodeproj
xcode_scheme: ios-travis-sample

script:
- xcodebuild clean test -project 'ios-travis-sample.xcodeproj' -scheme "ios-travis-sample" -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0'
