os: osx
osx_image: xcode9
language: objective-c
xcode_project: ios-travis-sample.xcodeproj
xcode_scheme: ios-travis-sample

matrix:
  include: # More Emulator API levels to build in parallel
    - env: OS=11.0
  allow_failures:
    - env: OS=10.0
    - env: OS=10.1
  fast_finish: false

script:
- xcodebuild clean build test -project 'ios-travis-sample.xcodeproj' -scheme "ios-travis-sample" -destination 'platform=iOS Simulator,name=iPhone 7,OS=${OS}'
